services:
  # Monitoring service
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    profiles: ["prod"]


volumes:
  prometheus_data:
